In [1]:
import numpy as np

# Part A - NumPy Operations

# Creating an array that starts from 1, ends at 20, and increments by 3.
array1 = np.arange(1, 21, 3)

# Generating a 3-element array with random numbers between 0 and 1.
array2 = np.random.rand(3)

# Working with a 2D array.
array3 = np.array([[10, 20, 45], [30, 12, 16], [42, 17, 56]])

# Slicing the first two rows.
first_two_rows = array3[:2, :]

# Extracting the last two rows.
last_two_rows = array3[1:, :]

# Creating two 2x2 arrays.
array4 = np.array([[1, 2], [3, 4]])
array5 = np.array([[5, 6], [7, 8]])

# Stacking elements vertically.
vertical_stack = np.vstack((array4, array5))

# Stacking elements horizontally.
horizontal_stack = np.hstack((array4, array5))

# Splitting the arrays back into smaller arrays.
split_vertical = np.vsplit(vertical_stack, 2)
split_horizontal = np.hsplit(horizontal_stack, 2)

# Matrices X and Y.
X = np.array([[5, 7, 2], [4, 5, 6], [7, 4, 2]])
Y = np.array([[4, 2], [6, 2], [4, 2]])

# Attempting matrix multiplication.
try:
    result = np.dot(X, Y)
except ValueError:
    result = "Matrix multiplication is not possible."

# Two arrays x and y.
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

# Finding the shape and number of dimensions of vector x.
shape_x = x.shape
dims_x = x.ndim

# Reshaping x into a matrix of size (3, 1).
x_reshaped = x.reshape(3, 1)

# Determining the number of dimensions after reshaping y into a matrix of (3, 1).
y_reshaped = y.reshape(3, 1)
dims_y_reshaped = y_reshaped.ndim

# Broadcasting example - subtracting a scalar from a matrix.
matrix_A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
scalar = 10
result_broadcasting = matrix_A - scalar


# Displaying the results.
print("Part A - NumPy Operations:")

print("Array 1:", array1)

print("Array 2:", array2)

print("Array 3:\n", array3)

print("First Two Rows of Array 3:\n", first_two_rows)

print("Last Two Rows of Array 3:\n", last_two_rows)

print("Array 4:\n", array4)

print("Array 5:\n", array5)

print("Vertical Stack of Array 4 and Array 5:\n", vertical_stack)

print("Horizontal Stack of Array 4 and Array 5:\n", horizontal_stack)

print("Split Vertical Stack (2 pieces):\n", split_vertical)

print("Split Horizontal Stack (2 pieces):\n", split_horizontal)

print("Matrix X:\n", X)

print("Matrix Y:\n", Y)

print("Matrix Multiplication Result (X * Y):\n", result)

print("Array x:", x)

print("Array y:", y)

print("Shape of Vector x:", shape_x)

print("Number of Dimensions of Vector x:", dims_x)

print("Reshaped Vector x (3x1):\n", x_reshaped)

print("Number of Dimensions of Reshaped Vector y (3x1):", dims_y_reshaped)

print("Result of Broadcasting (Matrix A - Scalar):\n", result_broadcasting)


Part A - NumPy Operations:
Array 1: [ 1  4  7 10 13 16 19]
Array 2: [0.52900639 0.22674016 0.60366626]
Array 3:
 [[10 20 45]
 [30 12 16]
 [42 17 56]]
First Two Rows of Array 3:
 [[10 20 45]
 [30 12 16]]
Last Two Rows of Array 3:
 [[30 12 16]
 [42 17 56]]
Array 4:
 [[1 2]
 [3 4]]
Array 5:
 [[5 6]
 [7 8]]
Vertical Stack of Array 4 and Array 5:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal Stack of Array 4 and Array 5:
 [[1 2 5 6]
 [3 4 7 8]]
Split Vertical Stack (2 pieces):
 [array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]
Split Horizontal Stack (2 pieces):
 [array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]
Matrix X:
 [[5 7 2]
 [4 5 6]
 [7 4 2]]
Matrix Y:
 [[4 2]
 [6 2]
 [4 2]]
Matrix Multiplication Result (X * Y):
 [[70 28]
 [70 30]
 [60 26]]
Array x: [ 2 -1 -8]
Array y: [ 3  1 -2]
Shape of Vector x: (3,)
Number of Dimensions of Vector x: 1
Reshaped Vector x (3x1):
 [[ 2]
 [-1]
 [-8]]
Number of Dimensions of Reshaped Vector y (3x1): 2
Result of Broadcasting (Ma

In [2]:
import numpy as np

# Part B - Linear Equations

# Part B.1: System of Equations
A1 = np.array([[4, 1, -2], [2, -3, 2], [1, 2, 3]])
b1 = np.array([10, -4, 6])

# Checking if the system is singular.
is_singular1 = np.linalg.matrix_rank(A1) < A1.shape[0]

# Solving the system if it's not singular.
if not is_singular1:
    x1 = np.linalg.solve(A1, b1)

# Part B.2: Another System of Equations
A2 = np.array([[2, -1, 3, 4], [4, -2, 6, 8], [3, 1, -2, 2], [1, 3, -4, 1]])
b2 = np.array([10, 20, 3, -1])

# Checking if the system is singular.
is_singular2 = np.linalg.matrix_rank(A2) < A2.shape[0]

# Solving the system if it's not singular.
if not is_singular2:
    x2 = np.linalg.solve(A2, b2)

# Displaying the results.
print("\nPart B - Linear Equations:")
if not is_singular1:
    print("Solution for Part B.1:", x1)
else:
    print("System B.1 is singular and cannot be solved.")

if not is_singular2:
    print("Solution for Part B.2:", x2)
else:
    print("System B.2 is singular and cannot be solved.")






Part B - Linear Equations:
Solution for Part B.1: [ 1.8  2.4 -0.2]
System B.2 is singular and cannot be solved.
